version: '3.8'

services:
  agentic-pentest:
    build: .
    container_name: ai_pentest_framework
    volumes:
      - .:/app
    env_file:
      - .env
    # Default target if none is specified when running `docker-compose run agentic-pentest`
    command: python -m watchtower.main -t https://www.edityourdockercompose.com
